build:
  image: golang:latest
  stage: build
  tags:
      - dind
  only:
      - tags
  script:
    - go build -o dbmigrate
    - GOOS=windows go build -o dbmigrate.exe 
  artifacts:
    name: 'dbmigrate_$CI_COMMIT_TAG'
    paths: ['dbmigrate', 'dbmigrate.exe']

build-docker:
  stage: build-docker
  only:
    refs:
      - tags
  tags:
    - docker
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --build-arg VERSION="${CI_COMMIT_TAG}" --build-arg COMMIT=${CI_COMMIT_SHORT_SHA} --build-arg DEPLOY_USER_COMPOSER=${DEPLOY_USER_COMPOSER} --build-arg DEPLOY_TOKEN_COMPOSER=${DEPLOY_TOKEN_COMPOSER} --build-arg DEPLOY_TOKEN_NPM=${DEPLOY_TOKEN_NPM} -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"